server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端实例名称
  client:
    # false便是不想注册中心注册自己
    register-with-eureka: false
    # false便是自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      degayltZone: http://eureka7001.com:7001/eureka/